import React from 'react'
import Link from 'next/link'
import { ArrowRight, ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { TextEffect } from '@/components/ui/text-effect'
import { AnimatedGroup } from '@/components/ui/animated-group'
import { HeroHeader } from './header'

const transitionVariants = {
    item: {
        hidden: {
            opacity: 0,
            filter: 'blur(12px)',
            y: 12,
        },
        visible: {
            opacity: 1,
            filter: 'blur(0px)',
            y: 0,
            transition: {
                type: 'spring' as const,
                bounce: 0.3,
                duration: 1.5,
            },
        },
    },
}

export default function HeroSection() {
    return (
        <>

            <HeroHeader />

            <main className="overflow-hidden">

                <div
                    aria-hidden
                    className="absolute inset-0 isolate hidden opacity-65 contain-strict lg:block">
                    <div className="w-140 h-320 -translate-y-87.5 absolute left-0 top-0 -rotate-45 rounded-full bg-[radial-gradient(68.54%_68.72%_at_55.02%_31.46%,hsla(0,0%,85%,.08)_0,hsla(0,0%,55%,.02)_50%,hsla(0,0%,45%,0)_80%)]" />
                    <div className="h-320 absolute left-0 top-0 w-60 -rotate-45 rounded-full bg-[radial-gradient(50%_50%_at_50%_50%,hsla(0,0%,85%,.06)_0,hsla(0,0%,45%,.02)_80%,transparent_100%)] [translate:5%_-50%]" />
                    <div className="h-320 -translate-y-87.5 absolute left-0 top-0 w-60 -rotate-45 bg-[radial-gradient(50%_50%_at_50%_50%,hsla(0,0%,85%,.04)_0,hsla(0,0%,45%,.02)_80%,transparent_100%)]" />
                </div>
                <section>
                    <div className="relative pt-24 md:pt-36">







                        <div className="mx-auto max-w-7xl px-6">
                            <div className="text-center sm:mx-auto lg:mr-auto lg:mt-0">


                                <TextEffect
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    as="span"
                                    className="mx-auto text-6xl text-yellow-500   font-bold md:text-7xl lg:mt-8 xl:text-[5.25rem]">
                                    AI-
                                </TextEffect>
                            
                                <TextEffect
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    as="span"
                                    className=" mx-auto text-6xl font-bold md:text-7xl lg:mt-8 xl:text-[5.25rem]">
                                Powered  
                                </TextEffect>
                                <TextEffect
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    as="span"
                                    className="text-yellow-500 ml-4 text-6xl font-bold md:text-7xl lg:mt-8 xl:text-[5.25rem]">
                                 Smartphone 
                                </TextEffect>
                                <TextEffect
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    as="span"
                                    className="text-yellow-500  mx-auto text-6xl font-bold md:text-7xl lg:mt-8 xl:text-[5.25rem]">
                                Reviews 
                                </TextEffect>
                                <TextEffect
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    as="span"
                                    className=" mx-auto text-6xl font-bold md:text-7xl lg:mt-8 xl:text-[5.25rem]">
                             – Fast, Accurate & Honest
                                </TextEffect>
                                <TextEffect
                                    per="line"
                                    preset="fade-in-blur"
                                    speedSegment={0.1}
                                    delay={0.5}
                                    as="p"
                                    className="mx-auto mt-8 max-w-2xl text-muted-foreground text-lg">
                                    Discover fast, accurate, and unbiased smartphone reviews generated by advanced AI. Compare specs, performance, cameras, and prices.
                                </TextEffect>

                           
                            </div>
                        </div>


                    </div> 
                </section>

            </main>
        </>
    )
}
